baseURL = "/"
title = "Jenkins X - Cloud Native CI/CD Built On Kubernetes"

enableRobotsTXT = true

ignorefiles = [ "docs/labs/.*" ]
# getting an error on the contributors plugin
ignoreErrors = ["error-remote-getjson"]

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]

# Setting this to false to keep builds from breaking: https://github.com/gohugoio/hugo/issues/6035
# Will give values to .Lastmod etc.
enableGitInfo = false

###
# Language configuration
###

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Useful when translating.
enableMissingTranslationPlaceholders = true

[languages]
[languages.en]
	title = "Jenkins X - Cloud Native CI/CD Built On Kubernetes"
	description = "Documentation, guides and support for Jenkins X"
	languageName ="English"
	# Weight used for sorting.
	weight = 1
[languages.zh]
	languageCode = "zh-CN"
	weight = 2
	languageName = "中文"
	contentDir = "content/zh"
[languages.es]
	languageCode = "es-ES"
	weight = 3
	languageName = "Español"
	contentDir = "content/es"

disableKinds = ["taxonomy", "taxonomyTerm"]

###
# Configure how URLs look like per section.
###
[permalinks]
	blog = "/:section/:year/:month/:day/:slug/"

###
# Configuration for Goldmark markdown parser
###
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

###
# Image processing configuration.
###
[imaging]
	resampleFilter = "CatmullRom"
	quality = 75
	anchor = "smart"

###
# Services
###

[services]
	[services.googleAnalytics]
	# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
		id = "UA-4216293-7"

###
# Everything below this are Site Params
###

[params]
## Used for views in rendered HTML (i.e., rather than using the .Hugo variable)
release = "3.16.25"

## the jx-lens version
jx_lens_version = "1.0.18"

copyright = "The Jenkins X Authors."
privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Documentation"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/jenkins-x/jx-docs"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/jenkins-x/jx"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/jenkins-x/jx-docs/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/jenkins-x/jx-docs/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Calendar"
	url = "/community/calendar/"
	icon = "fas fa-calendar-alt"
	desc = "Google Calendar for Jenkins X"
[[params.links.user]]
	name = "Youtube"
	url = "https://www.youtube.com/channel/UCN2kblPjXKMcjjVYmwvquvg"
	icon = "fab fa-youtube"
	desc = "Subscribe to the youtube Channel"
[[params.links.user]]
	name = "Github"
	url = "https://github.com/jenkins-x/jx"
	icon = "fab fa-github"
	desc = "Development takes place here!"
[[params.links.user]]
	name = "Contribute"
	url = "https://jenkins-x.io/community/documentation/"
	icon = "fas fa-edit"
	desc = "Contribute to the Jenkins X website"
[[params.links.user]]
	name = "User Slack Channel"
	url = "https://kubernetes.slack.com/messages/C9MBGQJRH"
	icon = "fab fa-slack"
	desc = "Discussion and help from your fellow users"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/jenkins-x/jx"
	icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
	name = "Developer Slack Channel"
	url = "https://kubernetes.slack.com/messages/C9LTHT2BB"
	icon = "fab fa-slack"
  desc = "Chat with other project developers"

# Versioning
[[params.versions]]
version = "v3.x (Current)"
url = "/v3/about"
dirpath = "v3"

[[params.versions]]
version = "v2.x (Unmaintained)"
url = "/docs"
dirpath = "docs"
